// generated by scripts/gen-db-types.sh — migrations sha256:e037dbc578faabf17827a2764454231b06ae30e5b675b037ba2ad13487bc8efc
// generated 2026-08-11T23:39:11Z from the dated cdk/sql chain applied to an ephemeral supabase/postgres:15.8.1.085
// do not edit by hand — re-run: bash scripts/gen-db-types.sh
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  competitor_intel: {
    Tables: {
      chunks: {
        Row: {
          content: string
          document_id: string
          embedded_at: string | null
          embedding: string | null
          embedding_model: string | null
          id: number
          seq: number
          token_estimate: number
        }
        Insert: {
          content: string
          document_id: string
          embedded_at?: string | null
          embedding?: string | null
          embedding_model?: string | null
          id?: never
          seq: number
          token_estimate: number
        }
        Update: {
          content?: string
          document_id?: string
          embedded_at?: string | null
          embedding?: string | null
          embedding_model?: string | null
          id?: never
          seq?: number
          token_estimate?: number
        }
        Relationships: [
          {
            foreignKeyName: "chunks_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
        ]
      }
      documents: {
        Row: {
          content: string
          created_at: string
          error: string | null
          id: string
          source_id: string
          status: string
          title: string
          updated_at: string
        }
        Insert: {
          content: string
          created_at?: string
          error?: string | null
          id?: string
          source_id: string
          status?: string
          title: string
          updated_at?: string
        }
        Update: {
          content?: string
          created_at?: string
          error?: string | null
          id?: string
          source_id?: string
          status?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "documents_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
        ]
      }
      sources: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          kind: string
          name: string
          notes: string | null
          updated_at: string
          url: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          kind?: string
          name: string
          notes?: string | null
          updated_at?: string
          url?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          kind?: string
          name?: string
          notes?: string | null
          updated_at?: string
          url?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      match_chunks: {
        Args: {
          filter_source_id?: string
          match_count?: number
          query_embedding: string
        }
        Returns: {
          chunk_id: number
          content: string
          document_id: string
          document_title: string
          embedding_model: string
          seq: number
          similarity: number
          source_id: string
          source_name: string
        }[]
      }
      search_chunks_fts: {
        Args: {
          filter_source_id?: string
          match_count?: number
          query_text: string
        }
        Returns: {
          chunk_id: number
          content: string
          document_id: string
          document_title: string
          rank: number
          seq: number
          source_id: string
          source_name: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  marketinghub: {
    Tables: {
      backup_status: {
        Row: {
          captured_at: string
          id: number
          payload: Json
        }
        Insert: {
          captured_at?: string
          id?: number
          payload: Json
        }
        Update: {
          captured_at?: string
          id?: number
          payload?: Json
        }
        Relationships: []
      }
      console_impersonation_audit: {
        Row: {
          actor_email: string
          claims: Json
          created_at: string
          error: string | null
          id: string
          row_count: number | null
          success: boolean
          target_schema: string
          target_table: string
        }
        Insert: {
          actor_email: string
          claims: Json
          created_at?: string
          error?: string | null
          id?: string
          row_count?: number | null
          success: boolean
          target_schema: string
          target_table: string
        }
        Update: {
          actor_email?: string
          claims?: Json
          created_at?: string
          error?: string | null
          id?: string
          row_count?: number | null
          success?: boolean
          target_schema?: string
          target_table?: string
        }
        Relationships: []
      }
      console_query_history: {
        Row: {
          duration_ms: number | null
          error: string | null
          id: string
          ran_at: string
          ran_by: string
          row_count: number | null
          sql: string
        }
        Insert: {
          duration_ms?: number | null
          error?: string | null
          id?: string
          ran_at?: string
          ran_by: string
          row_count?: number | null
          sql: string
        }
        Update: {
          duration_ms?: number | null
          error?: string | null
          id?: string
          ran_at?: string
          ran_by?: string
          row_count?: number | null
          sql?: string
        }
        Relationships: []
      }
      console_snippets: {
        Row: {
          created_at: string
          created_by: string
          id: string
          name: string
          sql: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by: string
          id?: string
          name: string
          sql: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string
          id?: string
          name?: string
          sql?: string
          updated_at?: string
        }
        Relationships: []
      }
      contact_list_members: {
        Row: {
          consent_date: string | null
          consent_source: string | null
          created_at: string
          first_name: string
          id: string
          list_id: string
          name: string
          phone_e164: string | null
          raw_phone: string
          reason: string
          timezone: string | null
        }
        Insert: {
          consent_date?: string | null
          consent_source?: string | null
          created_at?: string
          first_name?: string
          id?: string
          list_id: string
          name?: string
          phone_e164?: string | null
          raw_phone?: string
          reason?: string
          timezone?: string | null
        }
        Update: {
          consent_date?: string | null
          consent_source?: string | null
          created_at?: string
          first_name?: string
          id?: string
          list_id?: string
          name?: string
          phone_e164?: string | null
          raw_phone?: string
          reason?: string
          timezone?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contact_list_members_list_id_fkey"
            columns: ["list_id"]
            isOneToOne: false
            referencedRelation: "contact_lists"
            referencedColumns: ["id"]
          },
        ]
      }
      contact_lists: {
        Row: {
          contact_count: number
          created_at: string
          created_by: string
          duplicate_count: number
          id: string
          invalid_count: number
          monday_board_id: string | null
          monday_board_name: string | null
          monday_outcome_column_id: string | null
          monday_phone_column_id: string | null
          monday_timezone_column_id: string | null
          name: string
          original_filename: string | null
          source: string
          storage_path: string | null
          updated_at: string
        }
        Insert: {
          contact_count?: number
          created_at?: string
          created_by: string
          duplicate_count?: number
          id?: string
          invalid_count?: number
          monday_board_id?: string | null
          monday_board_name?: string | null
          monday_outcome_column_id?: string | null
          monday_phone_column_id?: string | null
          monday_timezone_column_id?: string | null
          name: string
          original_filename?: string | null
          source: string
          storage_path?: string | null
          updated_at?: string
        }
        Update: {
          contact_count?: number
          created_at?: string
          created_by?: string
          duplicate_count?: number
          id?: string
          invalid_count?: number
          monday_board_id?: string | null
          monday_board_name?: string | null
          monday_outcome_column_id?: string | null
          monday_phone_column_id?: string | null
          monday_timezone_column_id?: string | null
          name?: string
          original_filename?: string | null
          source?: string
          storage_path?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      edge_functions: {
        Row: {
          deployed_at: string | null
          name: string
          notes: string | null
          source: string
          updated_at: string
          version: string
        }
        Insert: {
          deployed_at?: string | null
          name: string
          notes?: string | null
          source: string
          updated_at?: string
          version?: string
        }
        Update: {
          deployed_at?: string | null
          name?: string
          notes?: string | null
          source?: string
          updated_at?: string
          version?: string
        }
        Relationships: []
      }
      sms_campaign_recipients: {
        Row: {
          attempts: number
          campaign_id: string
          claim_expires_at: string | null
          claimed_at: string | null
          created_at: string
          first_name: string | null
          id: string
          last_error: string | null
          monday_item_id: string | null
          monday_synced_at: string | null
          monday_synced_status: string | null
          name: string | null
          phone_e164: string | null
          rendered_text: string
          send_after: string
          send_timezone: string | null
          st_credits: number | null
          st_message_id: string | null
          status: string
          updated_at: string
        }
        Insert: {
          attempts?: number
          campaign_id: string
          claim_expires_at?: string | null
          claimed_at?: string | null
          created_at?: string
          first_name?: string | null
          id?: string
          last_error?: string | null
          monday_item_id?: string | null
          monday_synced_at?: string | null
          monday_synced_status?: string | null
          name?: string | null
          phone_e164?: string | null
          rendered_text: string
          send_after: string
          send_timezone?: string | null
          st_credits?: number | null
          st_message_id?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          attempts?: number
          campaign_id?: string
          claim_expires_at?: string | null
          claimed_at?: string | null
          created_at?: string
          first_name?: string | null
          id?: string
          last_error?: string | null
          monday_item_id?: string | null
          monday_synced_at?: string | null
          monday_synced_status?: string | null
          name?: string | null
          phone_e164?: string | null
          rendered_text?: string
          send_after?: string
          send_timezone?: string | null
          st_credits?: number | null
          st_message_id?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sms_campaign_recipients_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "sms_campaign_engagement"
            referencedColumns: ["campaign_id"]
          },
          {
            foreignKeyName: "sms_campaign_recipients_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "sms_campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      sms_campaigns: {
        Row: {
          contact_list_id: string | null
          created_at: string
          created_by: string
          id: string
          message_body: string
          monday_board_id: string | null
          monday_phone_column_id: string | null
          name: string
          send_at: string
          send_date: string
          send_time: string
          send_timezone: string
          status: string
          template_id: string
          updated_at: string
        }
        Insert: {
          contact_list_id?: string | null
          created_at?: string
          created_by: string
          id?: string
          message_body: string
          monday_board_id?: string | null
          monday_phone_column_id?: string | null
          name: string
          send_at: string
          send_date: string
          send_time?: string
          send_timezone?: string
          status?: string
          template_id: string
          updated_at?: string
        }
        Update: {
          contact_list_id?: string | null
          created_at?: string
          created_by?: string
          id?: string
          message_body?: string
          monday_board_id?: string | null
          monday_phone_column_id?: string | null
          name?: string
          send_at?: string
          send_date?: string
          send_time?: string
          send_timezone?: string
          status?: string
          template_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sms_campaigns_contact_list_id_fkey"
            columns: ["contact_list_id"]
            isOneToOne: false
            referencedRelation: "contact_lists"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sms_campaigns_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "templates"
            referencedColumns: ["id"]
          },
        ]
      }
      sms_inbound_messages: {
        Row: {
          body: string
          handled: boolean
          handled_at: string | null
          handled_by: string | null
          id: string
          matched_campaign_id: string | null
          matched_recipient_id: string | null
          phone_e164: string | null
          raw: Json
          received_at: string
        }
        Insert: {
          body?: string
          handled?: boolean
          handled_at?: string | null
          handled_by?: string | null
          id?: string
          matched_campaign_id?: string | null
          matched_recipient_id?: string | null
          phone_e164?: string | null
          raw: Json
          received_at?: string
        }
        Update: {
          body?: string
          handled?: boolean
          handled_at?: string | null
          handled_by?: string | null
          id?: string
          matched_campaign_id?: string | null
          matched_recipient_id?: string | null
          phone_e164?: string | null
          raw?: Json
          received_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sms_inbound_messages_matched_campaign_id_fkey"
            columns: ["matched_campaign_id"]
            isOneToOne: false
            referencedRelation: "sms_campaign_engagement"
            referencedColumns: ["campaign_id"]
          },
          {
            foreignKeyName: "sms_inbound_messages_matched_campaign_id_fkey"
            columns: ["matched_campaign_id"]
            isOneToOne: false
            referencedRelation: "sms_campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sms_inbound_messages_matched_recipient_id_fkey"
            columns: ["matched_recipient_id"]
            isOneToOne: false
            referencedRelation: "sms_campaign_recipients"
            referencedColumns: ["id"]
          },
        ]
      }
      sms_link_clicks: {
        Row: {
          clicked_at: string
          id: string
          link_id: string
          user_agent: string | null
        }
        Insert: {
          clicked_at?: string
          id?: string
          link_id: string
          user_agent?: string | null
        }
        Update: {
          clicked_at?: string
          id?: string
          link_id?: string
          user_agent?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sms_link_clicks_link_id_fkey"
            columns: ["link_id"]
            isOneToOne: false
            referencedRelation: "sms_links"
            referencedColumns: ["id"]
          },
        ]
      }
      sms_links: {
        Row: {
          campaign_id: string
          created_at: string
          id: string
          recipient_id: string
          slug: string
          target_url: string
        }
        Insert: {
          campaign_id: string
          created_at?: string
          id?: string
          recipient_id: string
          slug: string
          target_url: string
        }
        Update: {
          campaign_id?: string
          created_at?: string
          id?: string
          recipient_id?: string
          slug?: string
          target_url?: string
        }
        Relationships: [
          {
            foreignKeyName: "sms_links_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "sms_campaign_engagement"
            referencedColumns: ["campaign_id"]
          },
          {
            foreignKeyName: "sms_links_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "sms_campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sms_links_recipient_id_fkey"
            columns: ["recipient_id"]
            isOneToOne: false
            referencedRelation: "sms_campaign_recipients"
            referencedColumns: ["id"]
          },
        ]
      }
      sms_suppression_audit: {
        Row: {
          action: string
          actor: string
          created_at: string
          id: string
          note: string | null
          phone_e164: string
          reason: string
        }
        Insert: {
          action: string
          actor: string
          created_at?: string
          id?: string
          note?: string | null
          phone_e164: string
          reason: string
        }
        Update: {
          action?: string
          actor?: string
          created_at?: string
          id?: string
          note?: string | null
          phone_e164?: string
          reason?: string
        }
        Relationships: []
      }
      sms_suppressions: {
        Row: {
          created_at: string
          phone_e164: string
          raw: Json | null
          reason: string
        }
        Insert: {
          created_at?: string
          phone_e164: string
          raw?: Json | null
          reason: string
        }
        Update: {
          created_at?: string
          phone_e164?: string
          raw?: Json | null
          reason?: string
        }
        Relationships: []
      }
      sms_webhook_events: {
        Row: {
          id: string
          kind: string
          matched_recipient_id: string | null
          raw: Json
          received_at: string
        }
        Insert: {
          id?: string
          kind: string
          matched_recipient_id?: string | null
          raw: Json
          received_at?: string
        }
        Update: {
          id?: string
          kind?: string
          matched_recipient_id?: string | null
          raw?: Json
          received_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sms_webhook_events_matched_recipient_id_fkey"
            columns: ["matched_recipient_id"]
            isOneToOne: false
            referencedRelation: "sms_campaign_recipients"
            referencedColumns: ["id"]
          },
        ]
      }
      templates: {
        Row: {
          body: string
          category: string
          created_at: string
          created_by: string
          id: string
          name: string
          search: unknown
          storage_path: string | null
          subject: string | null
          tags: string[]
          type: string
          updated_at: string
        }
        Insert: {
          body: string
          category: string
          created_at?: string
          created_by: string
          id?: string
          name: string
          search?: unknown
          storage_path?: string | null
          subject?: string | null
          tags?: string[]
          type: string
          updated_at?: string
        }
        Update: {
          body?: string
          category?: string
          created_at?: string
          created_by?: string
          id?: string
          name?: string
          search?: unknown
          storage_path?: string | null
          subject?: string | null
          tags?: string[]
          type?: string
          updated_at?: string
        }
        Relationships: []
      }
      vault_console_audit: {
        Row: {
          action: string
          actor: string
          created_at: string
          id: number
          secret_id: string | null
          secret_name: string | null
        }
        Insert: {
          action: string
          actor: string
          created_at?: string
          id?: never
          secret_id?: string | null
          secret_name?: string | null
        }
        Update: {
          action?: string
          actor?: string
          created_at?: string
          id?: never
          secret_id?: string | null
          secret_name?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      sms_campaign_engagement: {
        Row: {
          campaign_id: string | null
          opt_outs: number | null
          recipients_clicked: number | null
          replies: number | null
          total_clicks: number | null
          tracked_links: number | null
          unhandled_replies: number | null
        }
        Insert: {
          campaign_id?: string | null
          opt_outs?: never
          recipients_clicked?: never
          replies?: never
          total_clicks?: never
          tracked_links?: never
          unhandled_replies?: never
        }
        Update: {
          campaign_id?: string | null
          opt_outs?: never
          recipients_clicked?: never
          replies?: never
          total_clicks?: never
          tracked_links?: never
          unhandled_replies?: never
        }
        Relationships: []
      }
      sms_campaign_recipient_counts: {
        Row: {
          campaign_id: string | null
          count: number | null
          status: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sms_campaign_recipients_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "sms_campaign_engagement"
            referencedColumns: ["campaign_id"]
          },
          {
            foreignKeyName: "sms_campaign_recipients_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "sms_campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      sms_campaign_recipient_zone_counts: {
        Row: {
          campaign_id: string | null
          count: number | null
          send_timezone: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sms_campaign_recipients_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "sms_campaign_engagement"
            referencedColumns: ["campaign_id"]
          },
          {
            foreignKeyName: "sms_campaign_recipients_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "sms_campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      claim_due_sms_recipients: {
        Args: {
          batch_size?: number
          claim_ttl_seconds?: number
          freq_cap_count?: number
          freq_cap_days?: number
        }
        Returns: {
          attempts: number
          campaign_id: string
          claim_expires_at: string | null
          claimed_at: string | null
          created_at: string
          first_name: string | null
          id: string
          last_error: string | null
          monday_item_id: string | null
          monday_synced_at: string | null
          monday_synced_status: string | null
          name: string | null
          phone_e164: string | null
          rendered_text: string
          send_after: string
          send_timezone: string | null
          st_credits: number | null
          st_message_id: string | null
          status: string
          updated_at: string
        }[]
        SetofOptions: {
          from: "*"
          to: "sms_campaign_recipients"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      custom_access_token_hook: { Args: { event: Json }; Returns: Json }
      templates_search: {
        Args: {
          p_body: string
          p_category: string
          p_name: string
          p_tags: string[]
        }
        Returns: unknown
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      wrappers_fdw_stats: {
        Row: {
          bytes_in: number | null
          bytes_out: number | null
          create_times: number | null
          created_at: string
          fdw_name: string
          metadata: Json | null
          rows_in: number | null
          rows_out: number | null
          updated_at: string
        }
        Insert: {
          bytes_in?: number | null
          bytes_out?: number | null
          create_times?: number | null
          created_at?: string
          fdw_name: string
          metadata?: Json | null
          rows_in?: number | null
          rows_out?: number | null
          updated_at?: string
        }
        Update: {
          bytes_in?: number | null
          bytes_out?: number | null
          create_times?: number | null
          created_at?: string
          fdw_name?: string
          metadata?: Json | null
          rows_in?: number | null
          rows_out?: number | null
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      airtable_fdw_handler: { Args: never; Returns: unknown }
      airtable_fdw_meta: {
        Args: never
        Returns: {
          author: string
          name: string
          version: string
          website: string
        }[]
      }
      airtable_fdw_validator: {
        Args: { catalog: unknown; options: string[] }
        Returns: undefined
      }
      auth0_fdw_handler: { Args: never; Returns: unknown }
      auth0_fdw_meta: {
        Args: never
        Returns: {
          author: string
          name: string
          version: string
          website: string
        }[]
      }
      auth0_fdw_validator: {
        Args: { catalog: unknown; options: string[] }
        Returns: undefined
      }
      big_query_fdw_handler: { Args: never; Returns: unknown }
      big_query_fdw_meta: {
        Args: never
        Returns: {
          author: string
          name: string
          version: string
          website: string
        }[]
      }
      big_query_fdw_validator: {
        Args: { catalog: unknown; options: string[] }
        Returns: undefined
      }
      click_house_fdw_handler: { Args: never; Returns: unknown }
      click_house_fdw_meta: {
        Args: never
        Returns: {
          author: string
          name: string
          version: string
          website: string
        }[]
      }
      click_house_fdw_validator: {
        Args: { catalog: unknown; options: string[] }
        Returns: undefined
      }
      cognito_fdw_handler: { Args: never; Returns: unknown }
      cognito_fdw_meta: {
        Args: never
        Returns: {
          author: string
          name: string
          version: string
          website: string
        }[]
      }
      cognito_fdw_validator: {
        Args: { catalog: unknown; options: string[] }
        Returns: undefined
      }
      firebase_fdw_handler: { Args: never; Returns: unknown }
      firebase_fdw_meta: {
        Args: never
        Returns: {
          author: string
          name: string
          version: string
          website: string
        }[]
      }
      firebase_fdw_validator: {
        Args: { catalog: unknown; options: string[] }
        Returns: undefined
      }
      hello_world_fdw_handler: { Args: never; Returns: unknown }
      hello_world_fdw_meta: {
        Args: never
        Returns: {
          author: string
          name: string
          version: string
          website: string
        }[]
      }
      hello_world_fdw_validator: {
        Args: { catalog: unknown; options: string[] }
        Returns: undefined
      }
      logflare_fdw_handler: { Args: never; Returns: unknown }
      logflare_fdw_meta: {
        Args: never
        Returns: {
          author: string
          name: string
          version: string
          website: string
        }[]
      }
      logflare_fdw_validator: {
        Args: { catalog: unknown; options: string[] }
        Returns: undefined
      }
      mssql_fdw_handler: { Args: never; Returns: unknown }
      mssql_fdw_meta: {
        Args: never
        Returns: {
          author: string
          name: string
          version: string
          website: string
        }[]
      }
      mssql_fdw_validator: {
        Args: { catalog: unknown; options: string[] }
        Returns: undefined
      }
      redis_fdw_handler: { Args: never; Returns: unknown }
      redis_fdw_meta: {
        Args: never
        Returns: {
          author: string
          name: string
          version: string
          website: string
        }[]
      }
      redis_fdw_validator: {
        Args: { catalog: unknown; options: string[] }
        Returns: undefined
      }
      s3_fdw_handler: { Args: never; Returns: unknown }
      s3_fdw_meta: {
        Args: never
        Returns: {
          author: string
          name: string
          version: string
          website: string
        }[]
      }
      s3_fdw_validator: {
        Args: { catalog: unknown; options: string[] }
        Returns: undefined
      }
      stripe_fdw_handler: { Args: never; Returns: unknown }
      stripe_fdw_meta: {
        Args: never
        Returns: {
          author: string
          name: string
          version: string
          website: string
        }[]
      }
      stripe_fdw_validator: {
        Args: { catalog: unknown; options: string[] }
        Returns: undefined
      }
      wasm_fdw_handler: { Args: never; Returns: unknown }
      wasm_fdw_meta: {
        Args: never
        Returns: {
          author: string
          name: string
          version: string
          website: string
        }[]
      }
      wasm_fdw_validator: {
        Args: { catalog: unknown; options: string[] }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  storage: {
    Tables: {
      buckets: {
        Row: {
          created_at: string | null
          id: string
          name: string
          owner: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          id: string
          name: string
          owner?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          name?: string
          owner?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      migrations: {
        Row: {
          executed_at: string | null
          hash: string
          id: number
          name: string
        }
        Insert: {
          executed_at?: string | null
          hash: string
          id: number
          name: string
        }
        Update: {
          executed_at?: string | null
          hash?: string
          id?: number
          name?: string
        }
        Relationships: []
      }
      objects: {
        Row: {
          bucket_id: string | null
          created_at: string | null
          id: string
          last_accessed_at: string | null
          metadata: Json | null
          name: string | null
          owner: string | null
          updated_at: string | null
        }
        Insert: {
          bucket_id?: string | null
          created_at?: string | null
          id?: string
          last_accessed_at?: string | null
          metadata?: Json | null
          name?: string | null
          owner?: string | null
          updated_at?: string | null
        }
        Update: {
          bucket_id?: string | null
          created_at?: string | null
          id?: string
          last_accessed_at?: string | null
          metadata?: Json | null
          name?: string | null
          owner?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "objects_bucketId_fkey"
            columns: ["bucket_id"]
            isOneToOne: false
            referencedRelation: "buckets"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      extension: { Args: { name: string }; Returns: string }
      filename: { Args: { name: string }; Returns: string }
      foldername: { Args: { name: string }; Returns: string[] }
      search: {
        Args: {
          bucketname: string
          levels?: number
          limits?: number
          offsets?: number
          prefix: string
        }
        Returns: {
          created_at: string
          id: string
          last_accessed_at: string
          metadata: Json
          name: string
          updated_at: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  vault: {
    Tables: {
      secrets: {
        Row: {
          created_at: string
          description: string
          id: string
          key_id: string | null
          name: string | null
          nonce: string | null
          secret: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string
          id?: string
          key_id?: string | null
          name?: string | null
          nonce?: string | null
          secret: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string
          id?: string
          key_id?: string | null
          name?: string | null
          nonce?: string | null
          secret?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      decrypted_secrets: {
        Row: {
          created_at: string | null
          decrypted_secret: string | null
          description: string | null
          id: string | null
          key_id: string | null
          name: string | null
          nonce: string | null
          secret: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          decrypted_secret?: never
          description?: string | null
          id?: string | null
          key_id?: string | null
          name?: string | null
          nonce?: string | null
          secret?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          decrypted_secret?: never
          description?: string | null
          id?: string | null
          key_id?: string | null
          name?: string | null
          nonce?: string | null
          secret?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      _crypto_aead_det_decrypt: {
        Args: {
          additional: string
          context?: string
          key_id: number
          message: string
          nonce?: string
        }
        Returns: string
      }
      _crypto_aead_det_encrypt: {
        Args: {
          additional: string
          context?: string
          key_id: number
          message: string
          nonce?: string
        }
        Returns: string
      }
      _crypto_aead_det_noncegen: { Args: never; Returns: string }
      create_secret: {
        Args: {
          new_description?: string
          new_key_id?: string
          new_name?: string
          new_secret: string
        }
        Returns: string
      }
      update_secret: {
        Args: {
          new_description?: string
          new_key_id?: string
          new_name?: string
          new_secret?: string
          secret_id: string
        }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  competitor_intel: {
    Enums: {},
  },
  marketinghub: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
  storage: {
    Enums: {},
  },
  vault: {
    Enums: {},
  },
} as const

