// @vitest-environment node
// Drift guard for the generated database.types.ts (scripts/gen-db-types.sh).
// The generator stamps line 1 with the sha256 of the sorted DATED cdk/sql
// migration files concatenated; this test recomputes that hash from the repo.
// When it fails, the dated migration chain changed after the last generation:
// re-run `bash scripts/gen-db-types.sh` (or, from web/: `npm run gen:types`)
// and commit the regenerated file. Never edit database.types.ts by hand.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const here = path.dirname(fileURLToPath(import.meta.url));
const sqlDir = path.resolve(here, "../../../cdk/sql");
const typesFile = path.resolve(here, "database.types.ts");

/**
 * Dated migrations only — mirrors the generator's
 * [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-*.sql glob. Utility files
 * (rls-gate.sql, enable-*.sql, lockdown-*.sql) are not part of the chain.
 */
const DATED = /^\d{4}-\d{2}-\d{2}-.*\.sql$/;

describe("database.types.ts drift guard", () => {
  it("starts with the generator header", () => {
    const firstLine = readFileSync(typesFile, "utf8").split("\n", 1)[0];
    expect(firstLine).toMatch(
      /^\/\/ generated by scripts\/gen-db-types\.sh — migrations sha256:[0-9a-f]{64}$/,
    );
  });

  it("header hash matches the dated cdk/sql chain (fails => re-run scripts/gen-db-types.sh)", () => {
    // ASCII-only names: JS code-unit sort === the generator's LC_ALL=C glob order.
    const files = readdirSync(sqlDir)
      .filter((f) => DATED.test(f))
      .sort();
    expect(files.length).toBeGreaterThan(0);

    const hash = createHash("sha256");
    for (const f of files) hash.update(readFileSync(path.join(sqlDir, f)));
    const expected = hash.digest("hex");

    const firstLine = readFileSync(typesFile, "utf8").split("\n", 1)[0];
    const stamped = firstLine.match(/migrations sha256:([0-9a-f]{64})/)?.[1];
    expect(
      stamped,
      "database.types.ts is missing the generator hash header",
    ).toBeDefined();
    expect(
      stamped,
      `migration chain changed since generation — re-run: bash scripts/gen-db-types.sh (dated files: ${files.join(", ")})`,
    ).toBe(expected);
  });

  it("exposes the Database type with all four generated schemas", () => {
    const source = readFileSync(typesFile, "utf8");
    expect(source).toContain("export type Database");
    for (const schema of ["marketinghub", "public", "storage", "vault"]) {
      expect(source, `schema ${schema} missing from generated types`).toMatch(
        new RegExp(`^  ${schema}: \\{`, "m"),
      );
    }
  });
});
